title: Salvium Blog
description: Official blog for Salvium Protocol
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Salvium Team"
